apiVersion: v1
kind: Service
metadata:
  name: nepse-service
spec:
  selector:
    app: nepse
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Use LoadBalancer if you want to expose the service externally
